 

# Site settings
title: Flavio H Sousa
email: flavioh007@gmail.com
description:  
  C# .Net web developer for the past 3 years. I love working with C# and web development. 
  In my current job I use JavaScript, JQuery, C#, .Net, Visual Studio, and Azure. 
 
url: "https://fhs2020.github.io/fhs-web-developer/" # the base hostname & protocol for your site

github_username:  fhs2020

 

