# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flavio H Sousa
email: flavioh007@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  C# .Net web developer for the past 3 years. I love working with C# and web development. 
  In my current job I use JavaScript, JQuery, C#, .Net, Visual Studio, and Azure. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fhs2020.github.io/fhs-web-developer/" # the base hostname & protocol for your site

github_username:  fhs2020

# Build settings

